name: rad_env
channels:
  - conda-forge
dependencies:
  - python=3.6.5
  - pandas=0.22.0
  - numpy=1.14.2
  - tqdm=4.23.0
  - scikit-learn=0.19.0
  - nltk=3.2.5
  - gensim=3.4.0
  - xlrd=1.1.0
  - jupyterlab
  - nb_conda
