name: rad_env
channels:
  - conda-forge
dependencies:
  - python=3.6.5
  - pandas=0.22.0
  - numpy=1.14.2
  - tqdm=4.23.0
  - scikit-learn=0.19.0
  - xlrd=1.1.0
  - jupyterlab=0.35.0
  - nb_conda_kernels=2.1.1
  - nltk=3.4.4
  - gensim=3.5.0
